// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICarbonAdd: typeof import('~icons/carbon/add')['default']
    ICarbonAddAlt: typeof import('~icons/carbon/add-alt')['default']
    ICarbonAddFilled: typeof import('~icons/carbon/add-filled')['default']
    ICarbonPlus: typeof import('~icons/carbon/plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
